force-app/main/default/objects/OrderInvoice__c/OrderInvoice__c.object-meta.xml
<CustomObject>
    <label>OrderInvoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>OrderInvoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderInvoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderInvoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderInvoices</relationshipLabel>
    <relationshipName>OrderInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderTriggerHandler.cls
public class OrderTriggerHandler {
    
    public static void createInvoice(List<Order> orderList, Map<Id, Order> orderMap){
        List<OrderInvoice__c> invoice = new List<OrderInvoice__c>();
        
        for(Order ord: orderList){
            Order oldOrder = orderMap.get(ord.Id);
            System.debug('invoice creation: '+ ord);
            if(ord.Status == 'Activated' && oldOrder.Status != 'Activated'){
                OrderInvoice__c inv = new OrderInvoice__c();
                inv.Order__c = ord.Id;
                inv.Status__c = 'Pending';
                invoice.add(inv);
            }
        }
        if(!invoice.isEmpty()){
            insert invoice;
        }
    }
}