force-app/main/default/objects/OrderInvoice__c/OrderInvoice__c.object-meta.xml
<CustomObject>
    <label>OrderInvoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>OrderInvoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderInvoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderInvoice__c/fields/Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Invoice Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderInvoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OrderInvoices</relationshipLabel>
    <relationshipName>OrderInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderInvoice__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>OrderInvoices</relationshipLabel>
    <relationshipName>OrderInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderInvoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <formula>Order__r.TotalAmount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InvoiceExtension.cls
public class InvoiceExtension {
    public OrderInvoice__c invoice { get; set; }
    public List<OrderItem> orderItems { get; set; }

    public InvoiceExtension(ApexPages.StandardController controller) {
        // Get Invoice ID from the page
        Id invoiceId = controller.getId();	
        
        // Fetch Invoice Details with Order Data
        invoice = [
            SELECT Id, Name, Total_Amount__c, Invoice_Date__c, 
                   Order__c, Order__r.OrderNumber, Order__r.BillingCountry, Order__r.BillingStreet,  Order__r.BillingCity, Order__r.BillingState, Order__r.BillingPostalCode,
                  Order__r.ShippingStreet, Order__r.ShippingCity, Order__r.ShippingState, Order__r.ShippingPostalCode, Order__r.ShippingCountry,
                   Opportunity__r.Account.Name
            FROM OrderInvoice__c 
            WHERE Id  = :invoiceId
            LIMIT 1
        ];

        // Fetch Order Items Related to this Order
        orderItems = [
            SELECT Id, Product2.Name, UnitPrice, Quantity, TotalPrice 
            FROM OrderItem 
            WHERE OrderId = :invoice.Order__c
        ];
    }
}