force-app/main/default/objects/OrderInvoice__c/OrderInvoice__c.object-meta.xml
<CustomObject>
    <label>OrderInvoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>OrderInvoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderInvoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderInvoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>OrderInvoices</relationshipLabel>
    <relationshipName>OrderInvoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderInvoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public class OpportunityTriggerHandler {
    
     
    public static void createInvoice(List<Opportunity> oppList){
        
        List<OrderInvoice__c> oInvList = new List<OrderInvoice__c>();
        
        for(Opportunity opp: oppList){
            OrderInvoice__c oInv = new OrderInvoice__c();
            oInv.Status__c = 'Pending';
            oInv.Opportunity__c = opp.Id;
            oInvList.add(oInv);
            
        }
        
        if(!oInvList.isEmpty()){
            insert oInvList;
        }
    }    
}